---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: chall-manager-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    # chall-manager
    - name: ctferio/chall-manager:v0.5.0
    - name: ctferio/chall-manager-janitor:v0.5.0
    - name: bitnami/etcd:3.5.16-debian-12-r0
    - name: library/busybox:1.28

---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: monitoring-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    # monitoring
    - name: jaegertracing/jaeger:2.8.0
    - name: otel/opentelemetry-collector-contrib:0.129.1
    - name: prom/prometheus:v3.4.2  
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: ctfer-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    - name: docker.io/bitnami/mariadb:11.4.5-debian-12-r12
    - name: docker.io/bitnami/redis:7.4.3-debian-12-r0
    - name: docker.io/ctferio/ctfd:3.7.7-0.4.0
---
apiVersion: content.hauler.cattle.io/v1
kind: Charts
metadata:
  name: ctfer-charts
spec:
  charts:
    - name: mariadb
      repoURL: oci://registry-1.docker.io/bitnamicharts
      version: 20.5.3
    - name: redis
      repoURL: oci://registry-1.docker.io/bitnamicharts
      version: 20.13.4
